import { NextRequest, NextResponse } from "next/server";
import { db } from "@/lib/db";
import { requireSession, logEvent } from "@/lib/auth";
import { handleError } from "@/lib/api";
import { generateSafetyFile } from "@/lib/ai";

export const maxDuration = 120;

export async function POST(_req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const session = await requireSession();
    const project = await db.project.findUnique({
      where: { id: params.id },
      include: { company: true },
    });
    if (!project || project.companyId !== session.companyId) {
      return NextResponse.json({ error: "Not found" }, { status: 404 });
    }

    const { content, generatedBy } = await generateSafetyFile({
      companyName: project.company.name,
      cidbGrade: project.company.cidbGrade,
      projectName: project.name,
      client: project.client,
      siteAddress: project.siteAddress,
      scope: project.scope,
      trades: project.trades,
      riskClass: project.riskClass,
      staffCount: project.staffCount,
      durationWeeks: project.durationWeeks,
    });

    const updated = await db.project.update({
      where: { id: project.id },
      data: { safetyFile: content, safetyFileAt: new Date(), safetyFileBy: generatedBy },
    });
    await db.job.create({
      data: {
        companyId: session.companyId,
        type: "safety_file",
        title: `QA review: safety file for ${project.name}`,
        status: "OPEN",
        notes: `Generated by ${generatedBy}. Human review required before delivery (SOP-02).`,
      },
    });
    await logEvent(session.companyId, session.userId, "safety_file.generated", project.name);
    return NextResponse.json({ project: updated, generatedBy });
  } catch (err) {
    return handleError(err);
  }
}
